---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - proxy.lindex.com
  resources:
  - tsproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxy.lindex.com
  resources:
  - tsproxies/finalizers
  verbs:
  - update
- apiGroups:
  - proxy.lindex.com
  resources:
  - tsproxies/status
  verbs:
  - get
  - patch
  - update
