# permissions for end users to edit tsproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tsproxy-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: tsproxy
    app.kubernetes.io/part-of: tsproxy
    app.kubernetes.io/managed-by: kustomize
  name: tsproxy-editor-role
rules:
- apiGroups:
  - proxy.lindex.com
  resources:
  - tsproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxy.lindex.com
  resources:
  - tsproxies/status
  verbs:
  - get
